<?php

namespace app\admin\controller;

use app\BaseController;
use app\library\Auth;
use app\library\Jwt;
use think\App;
use think\facade\Request;
use think\Response;

/**
 * 基控制器
 */
class Base extends BaseController
{
    /**
     * @var 用户
     */
    public $user;

    /**
     * 初始化
     * @return void
     */
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $auth = new Auth();
        if (!$auth->inNoLoginUrl()) {
            // 登录
            if (!$auth->isLogin()) {
                $this->error('登录已失效，请重新登录')->send();
                exit;
            }

            // 用户
            $this->user = $auth->getUser();

            // 权限
            if (!$auth->isPermission()) {
                $this->error('无权限')->send();
                exit;
            }
        }
    }

    /**
     * 成功响应
     * @param string $message 提示消息
     * @param mixed $data 返回数据
     */
    public function success(string $message, $data = null)
    {
        $result = [
            'code' => 1,
            'message' => $message,
            'data' => $data
        ];
        return Response::create($result, 'json', 200);
    }

    /**
     * 失败响应
     * @param string $message 提示消息
     * @param mixed $data 返回数据
     */
    public function error(string $message, $data = null)
    {
        $result = [
            'code' => 0,
            'message' => $message,
            'data' => $data
        ];
        return Response::create($result, 'json', 200);
    }
}
